In [1]:
import pandas as pd
import sqlalchemy
import sqlite3 as sq
from db_key import user, password, port, database, host, url

In [2]:
engine = sqlalchemy.create_engine(url) # connect to server
con = engine.connect()

In [3]:
df = pd.read_csv("../../Data/CSV_Files/Nat_Gas_Data.csv", encoding='utf-8')
df.head()

,Date,Total,Industrial,Electric,Residential,Commercial,Price_Elec,Price_Ind,Price_Com,Price_Res,Price_HH,Area,Prod
0,2002-01-01,2487.638,686.108,381.434,815.227,604.869,3.10,4.05,6.51,7.38,2.317619,U.S.,1618.892
1,2002-02-01,2242.427,632.621,344.243,712.863,552.700,2.86,3.70,6.40,7.23,2.323684,U.S.,1449.623
2,2002-03-01,2258.431,655.854,406.516,660.430,535.631,3.37,3.78,6.28,7.10,3.028500,U.S.,1619.570
3,2002-04-01,1880.985,646.534,404.384,415.196,414.871,3.80,3.64,6.56,7.66,3.426818,U.S.,1565.063
4,2002-05-01,1611.453,611.973,410.108,255.083,334.289,3.78,4.07,6.68,8.54,3.498182,U.S.,1628.885

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 208 entries, 0 to 207
Data columns (total 13 columns):
Date           208 non-null object
Total          208 non-null float64
Industrial     208 non-null float64
Electric       208 non-null float64
Residential    208 non-null float64
Commercial     208 non-null float64
Price_Elec     208 non-null float64
Price_Ind      208 non-null float64
Price_Com      208 non-null float64
Price_Res      208 non-null float64
Price_HH       208 non-null float64
Area           208 non-null object
Prod           208 non-null float64
dtypes: float64(11), object(2)
memory usage: 21.2+ KB

In [5]:
# df_GasDemand_US = df.loc[(df["Area"]=="U.S.") & (df["Unnamed: 0"]<=30)]
# df_GasDemand_US = df_GasDemand_US.drop(["Unnamed: 0"], axis=1)
df_GasDemand_US = df.copy()
df_GasDemand_US

,Date,Total,Industrial,Electric,Residential,Commercial,Price_Elec,Price_Ind,Price_Com,Price_Res,Price_HH,Area,Prod
0,2002-01-01,2487.638,686.108,381.434,815.227,604.869,3.10,4.05,6.51,7.38,2.317619,U.S.,1618.892
1,2002-02-01,2242.427,632.621,344.243,712.863,552.700,2.86,3.70,6.40,7.23,2.323684,U.S.,1449.623
2,2002-03-01,2258.431,655.854,406.516,660.430,535.631,3.37,3.78,6.28,7.10,3.028500,U.S.,1619.570
3,2002-04-01,1880.985,646.534,404.384,415.196,414.871,3.80,3.64,6.56,7.66,3.426818,U.S.,1565.063
4,2002-05-01,1611.453,611.973,410.108,255.083,334.289,3.78,4.07,6.68,8.54,3.498182,U.S.,1628.885
5,2002-06-01,1591.373,595.674,550.941,159.973,284.785,3.61,3.86,6.80,9.58,3.261500,U.S.,1569.228
6,2002-07-01,1748.435,605.786,733.887,125.065,283.697,3.49,3.80,6.62,10.31,2.987143,U.S.,1636.448
7,2002-08-01,1725.712,611.822,717.592,115.678,280.620,3.42,3.62,6.45,10.44,3.087727,U.S.,1603.278
8,2002-09-01,1542.170,573.310,568.699,123.904,276.257,3.71,3.89,6.54,10.23,3.549000,U.S.,1516.304
9,2002-10-01,1645.873,613.448,442.357,250.573,339.495,4.19,4.18,6.64,8.61,4.126522,U.S.,1551.787
10,2002-11-01,1913.629,632.273,351.612,483.192,446.552,4.35,4.72,6.89,7.99,4.043158,U.S.,1555.595
11,2002-12-01,2378.895,661.782,360.123,771.634,585.356,4.72,4.92,7.16,7.87,4.740952,U.S.,1613.115
12,2003-01-01,2700.545,687.821,382.443,945.975,684.306,5.33,5.65,7.48,8.18,5.432381,U.S.,1616.551
13,2003-02-01,2500.315,643.666,334.698,884.238,637.713,6.47,6.40,7.98,8.58,7.707895,U.S.,1469.711
14,2003-03-01,2197.936,615.956,361.243,674.582,546.155,7.05,8.27,9.20,9.77,5.933333,U.S.,1662.980
15,2003-04-01,1743.530,574.624,352.164,414.495,402.247,5.38,5.96,8.97,10.18,5.263333,U.S.,1592.310
16,2003-05-01,1514.697,557.167,394.021,247.693,315.816,5.70,5.78,8.71,10.79,5.813810,U.S.,1625.900
17,2003-06-01,1368.369,511.339,435.598,157.454,263.978,6.08,6.59,9.00,12.08,5.818571,U.S.,1574.488
18,2003-07-01,1600.484,574.374,630.270,126.624,269.216,5.45,5.69,8.73,12.75,5.026364,U.S.,1594.080
19,2003-08-01,1651.580,580.776,683.513,115.852,271.439,5.23,5.28,8.40,12.84,4.984762,U.S.,1626.469
20,2003-09-01,1428.554,564.407,468.510,128.621,267.016,5.12,5.32,8.41,12.31,4.620476,U.S.,1566.968
21,2003-10-01,1553.189,598.581,408.817,231.558,314.233,4.98,4.93,8.28,10.64,4.626957,U.S.,1620.293
22,2003-11-01,1753.642,596.599,348.129,413.663,395.251,4.85,5.19,8.36,9.77,4.470000,U.S.,1549.049
23,2003-12-01,2263.659,645.086,335.810,738.596,544.167,5.69,5.90,8.62,9.51,6.127619,U.S.,1599.746
24,2004-01-01,2675.834,680.076,361.401,962.910,671.447,6.37,6.72,9.06,9.71,6.138947,U.S.,1594.905
25,2004-02-01,2511.097,648.777,373.466,857.450,631.404,5.76,6.52,9.10,9.85,5.368947,U.S.,1477.801
26,2004-03-01,2100.921,627.150,375.203,591.428,507.140,5.50,5.97,9.05,10.03,5.393913,U.S.,1605.170
27,2004-04-01,1745.171,585.952,389.328,379.642,390.249,5.74,6.06,9.02,10.54,5.709048,U.S.,1551.873
28,2004-05-01,1573.043,568.079,485.114,213.645,306.205,6.30,6.34,9.23,11.63,6.333500,U.S.,1575.675
29,2004-06-01,1483.684,562.774,508.140,144.885,267.885,6.52,6.82,9.71,13.08,6.270476,U.S.,1542.230
...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,2016-11-01,2159.445,654.119,662.046,379.746,463.534,3.14,3.86,7.67,10.77,2.550476,U.S.,2160.600
179,2016-12-01,2866.273,734.194,670.787,794.164,667.128,4.15,4.27,7.27,9.06,3.591364,U.S.,2207.475
180,2017-01-01,2900.856,734.820,647.362,830.679,687.995,4.33,4.87,7.58,9.32,3.304545,U.S.,2201.625
181,2017-02-01,2329.116,650.397,558.740,579.313,540.666,3.74,4.56,7.89,10.01,2.853000,U.S.,2005.478
182,2017-03-01,2529.336,696.841,678.970,579.768,573.757,3.52,3.94,7.68,9.86,2.879565,U.S.,2272.302
183,2017-04-01,1927.859,632.002,623.889,278.910,393.058,3.50,4.13,8.04,11.34,3.102000,U.S.,2201.339
184,2017-05-01,1896.885,628.595,706.151,199.451,362.688,3.61,4.03,8.31,13.26,3.149565,U.S.,2270.937
185,2017-06-01,1912.074,614.517,854.087,124.038,319.432,3.41,4.06,8.75,16.06,2.975455,U.S.,2214.944
186,2017-07-01,2132.701,623.935,1074.275,107.423,327.068,3.32,3.93,8.81,17.86,2.984286,U.S.,2316.835
187,2017-08-01,2104.885,637.549,1033.682,103.832,329.822,3.27,3.79,8.76,18.22,2.901304,U.S.,2316.286
188,2017-09-01,1922.561,616.109,862.068,114.548,329.836,3.31,3.84,8.52,16.92,2.975714,U.S.,2275.128
189,2017-10-01,2036.943,657.005,779.799,205.068,395.071,3.27,3.79,7.97,13.36,2.878636,U.S.,2383.842
190,2017-11-01,2351.279,696.113,662.814,467.638,524.714,3.50,3.85,7.51,10.15,3.013636,U.S.,2369.513
191,2017-12-01,3065.777,761.315,768.229,821.617,714.616,3.81,4.21,7.42,9.29,2.822500,U.S.,2462.993
192,2018-01-01,3310.405,770.972,785.260,975.802,778.371,5.35,4.48,7.43,8.91,3.875500,U.S.,2415.266
193,2018-02-01,2700.253,689.088,701.253,686.844,623.068,3.74,4.86,7.82,9.64,2.670526,U.S.,2221.695
194,2018-03-01,2773.304,726.891,755.400,656.263,634.750,3.32,4.02,7.74,9.78,2.692857,U.S.,2484.793
195,2018-04-01,2336.221,686.787,707.388,438.565,503.481,3.25,3.90,7.66,10.04,2.796190,U.S.,2413.092
196,2018-05-01,2046.766,660.292,853.201,167.909,365.364,3.15,3.81,8.46,13.64,2.800909,U.S.,2520.538
197,2018-06-01,2050.342,638.919,952.471,118.892,340.060,3.21,3.78,8.65,16.51,2.967143,U.S.,2453.118
198,2018-07-01,2346.413,654.616,1235.633,105.470,350.694,3.41,3.76,8.93,17.92,2.832381,U.S.,2584.898
199,2018-08-01,2311.370,657.898,1195.340,99.325,358.807,3.39,3.67,8.74,18.63,2.961739,U.S.,2639.800
200,2018-09-01,2158.549,646.642,1044.507,112.072,355.328,3.21,3.75,8.64,17.31,2.995263,U.S.,2590.301
201,2018-10-01,2276.313,671.454,894.986,254.554,455.319,3.50,4.04,7.71,12.26,3.275217,U.S.,2702.488
202,2018-11-01,2687.995,726.304,756.296,595.468,609.927,4.32,4.51,7.35,9.43,4.091000,U.S.,2656.502
203,2018-12-01,2958.554,755.975,743.958,762.819,695.802,4.89,5.46,7.77,9.63,4.041667,U.S.,2756.095
204,2019-01-01,3379.295,791.035,834.116,949.438,804.706,4.16,5.04,7.75,9.43,3.123182,U.S.,2750.413
205,2019-02-01,2983.892,710.003,769.182,805.830,698.877,3.79,4.65,7.61,9.47,2.687500,U.S.,2506.257
206,2019-03-01,2882.561,740.796,792.262,685.904,663.599,3.59,4.33,7.47,9.48,2.948571,U.S.,2775.301
207,2019-04-01,2182.901,667.363,724.048,327.124,464.366,2.98,4.02,7.77,10.92,2.647143,U.S.,2707.738

In [6]:
df_GasDemand_US.shape

(208, 13)

In [7]:
# Upload dataframe to Postgres SQL table in Heroku database
df_GasDemand_US.to_sql(name="gasdemand", con = engine, if_exists = 'replace', index=False)

In [8]:
# import os

# if not os.environ.get('DYNO'):
#     import config
#     print(config.name)
    
# if os.environ.get("DATABASE_URL"):
#     url=os.environ["DATABASE_URL"]
# else:
#     url = config.url

# engine= sqlalchemy.create_engine(url)

In [9]:
df_test = pd.read_sql("SELECT * FROM gasdemand", engine)
df_test

,Date,Total,Industrial,Electric,Residential,Commercial,Price_Elec,Price_Ind,Price_Com,Price_Res,Price_HH,Area,Prod
0,2002-01-01,2487.638,686.108,381.434,815.227,604.869,3.10,4.05,6.51,7.38,2.317619,U.S.,1618.892
1,2002-02-01,2242.427,632.621,344.243,712.863,552.700,2.86,3.70,6.40,7.23,2.323684,U.S.,1449.623
2,2002-03-01,2258.431,655.854,406.516,660.430,535.631,3.37,3.78,6.28,7.10,3.028500,U.S.,1619.570
3,2002-04-01,1880.985,646.534,404.384,415.196,414.871,3.80,3.64,6.56,7.66,3.426818,U.S.,1565.063
4,2002-05-01,1611.453,611.973,410.108,255.083,334.289,3.78,4.07,6.68,8.54,3.498182,U.S.,1628.885
5,2002-06-01,1591.373,595.674,550.941,159.973,284.785,3.61,3.86,6.80,9.58,3.261500,U.S.,1569.228
6,2002-07-01,1748.435,605.786,733.887,125.065,283.697,3.49,3.80,6.62,10.31,2.987143,U.S.,1636.448
7,2002-08-01,1725.712,611.822,717.592,115.678,280.620,3.42,3.62,6.45,10.44,3.087727,U.S.,1603.278
8,2002-09-01,1542.170,573.310,568.699,123.904,276.257,3.71,3.89,6.54,10.23,3.549000,U.S.,1516.304
9,2002-10-01,1645.873,613.448,442.357,250.573,339.495,4.19,4.18,6.64,8.61,4.126522,U.S.,1551.787
10,2002-11-01,1913.629,632.273,351.612,483.192,446.552,4.35,4.72,6.89,7.99,4.043158,U.S.,1555.595
11,2002-12-01,2378.895,661.782,360.123,771.634,585.356,4.72,4.92,7.16,7.87,4.740952,U.S.,1613.115
12,2003-01-01,2700.545,687.821,382.443,945.975,684.306,5.33,5.65,7.48,8.18,5.432381,U.S.,1616.551
13,2003-02-01,2500.315,643.666,334.698,884.238,637.713,6.47,6.40,7.98,8.58,7.707895,U.S.,1469.711
14,2003-03-01,2197.936,615.956,361.243,674.582,546.155,7.05,8.27,9.20,9.77,5.933333,U.S.,1662.980
15,2003-04-01,1743.530,574.624,352.164,414.495,402.247,5.38,5.96,8.97,10.18,5.263333,U.S.,1592.310
16,2003-05-01,1514.697,557.167,394.021,247.693,315.816,5.70,5.78,8.71,10.79,5.813810,U.S.,1625.900
17,2003-06-01,1368.369,511.339,435.598,157.454,263.978,6.08,6.59,9.00,12.08,5.818571,U.S.,1574.488
18,2003-07-01,1600.484,574.374,630.270,126.624,269.216,5.45,5.69,8.73,12.75,5.026364,U.S.,1594.080
19,2003-08-01,1651.580,580.776,683.513,115.852,271.439,5.23,5.28,8.40,12.84,4.984762,U.S.,1626.469
20,2003-09-01,1428.554,564.407,468.510,128.621,267.016,5.12,5.32,8.41,12.31,4.620476,U.S.,1566.968
21,2003-10-01,1553.189,598.581,408.817,231.558,314.233,4.98,4.93,8.28,10.64,4.626957,U.S.,1620.293
22,2003-11-01,1753.642,596.599,348.129,413.663,395.251,4.85,5.19,8.36,9.77,4.470000,U.S.,1549.049
23,2003-12-01,2263.659,645.086,335.810,738.596,544.167,5.69,5.90,8.62,9.51,6.127619,U.S.,1599.746
24,2004-01-01,2675.834,680.076,361.401,962.910,671.447,6.37,6.72,9.06,9.71,6.138947,U.S.,1594.905
25,2004-02-01,2511.097,648.777,373.466,857.450,631.404,5.76,6.52,9.10,9.85,5.368947,U.S.,1477.801
26,2004-03-01,2100.921,627.150,375.203,591.428,507.140,5.50,5.97,9.05,10.03,5.393913,U.S.,1605.170
27,2004-04-01,1745.171,585.952,389.328,379.642,390.249,5.74,6.06,9.02,10.54,5.709048,U.S.,1551.873
28,2004-05-01,1573.043,568.079,485.114,213.645,306.205,6.30,6.34,9.23,11.63,6.333500,U.S.,1575.675
29,2004-06-01,1483.684,562.774,508.140,144.885,267.885,6.52,6.82,9.71,13.08,6.270476,U.S.,1542.230
...,...,...,...,...,...,...,...,...,...,...,...,...,...
178,2016-11-01,2159.445,654.119,662.046,379.746,463.534,3.14,3.86,7.67,10.77,2.550476,U.S.,2160.600
179,2016-12-01,2866.273,734.194,670.787,794.164,667.128,4.15,4.27,7.27,9.06,3.591364,U.S.,2207.475
180,2017-01-01,2900.856,734.820,647.362,830.679,687.995,4.33,4.87,7.58,9.32,3.304545,U.S.,2201.625
181,2017-02-01,2329.116,650.397,558.740,579.313,540.666,3.74,4.56,7.89,10.01,2.853000,U.S.,2005.478
182,2017-03-01,2529.336,696.841,678.970,579.768,573.757,3.52,3.94,7.68,9.86,2.879565,U.S.,2272.302
183,2017-04-01,1927.859,632.002,623.889,278.910,393.058,3.50,4.13,8.04,11.34,3.102000,U.S.,2201.339
184,2017-05-01,1896.885,628.595,706.151,199.451,362.688,3.61,4.03,8.31,13.26,3.149565,U.S.,2270.937
185,2017-06-01,1912.074,614.517,854.087,124.038,319.432,3.41,4.06,8.75,16.06,2.975455,U.S.,2214.944
186,2017-07-01,2132.701,623.935,1074.275,107.423,327.068,3.32,3.93,8.81,17.86,2.984286,U.S.,2316.835
187,2017-08-01,2104.885,637.549,1033.682,103.832,329.822,3.27,3.79,8.76,18.22,2.901304,U.S.,2316.286
188,2017-09-01,1922.561,616.109,862.068,114.548,329.836,3.31,3.84,8.52,16.92,2.975714,U.S.,2275.128
189,2017-10-01,2036.943,657.005,779.799,205.068,395.071,3.27,3.79,7.97,13.36,2.878636,U.S.,2383.842
190,2017-11-01,2351.279,696.113,662.814,467.638,524.714,3.50,3.85,7.51,10.15,3.013636,U.S.,2369.513
191,2017-12-01,3065.777,761.315,768.229,821.617,714.616,3.81,4.21,7.42,9.29,2.822500,U.S.,2462.993
192,2018-01-01,3310.405,770.972,785.260,975.802,778.371,5.35,4.48,7.43,8.91,3.875500,U.S.,2415.266
193,2018-02-01,2700.253,689.088,701.253,686.844,623.068,3.74,4.86,7.82,9.64,2.670526,U.S.,2221.695
194,2018-03-01,2773.304,726.891,755.400,656.263,634.750,3.32,4.02,7.74,9.78,2.692857,U.S.,2484.793
195,2018-04-01,2336.221,686.787,707.388,438.565,503.481,3.25,3.90,7.66,10.04,2.796190,U.S.,2413.092
196,2018-05-01,2046.766,660.292,853.201,167.909,365.364,3.15,3.81,8.46,13.64,2.800909,U.S.,2520.538
197,2018-06-01,2050.342,638.919,952.471,118.892,340.060,3.21,3.78,8.65,16.51,2.967143,U.S.,2453.118
198,2018-07-01,2346.413,654.616,1235.633,105.470,350.694,3.41,3.76,8.93,17.92,2.832381,U.S.,2584.898
199,2018-08-01,2311.370,657.898,1195.340,99.325,358.807,3.39,3.67,8.74,18.63,2.961739,U.S.,2639.800
200,2018-09-01,2158.549,646.642,1044.507,112.072,355.328,3.21,3.75,8.64,17.31,2.995263,U.S.,2590.301
201,2018-10-01,2276.313,671.454,894.986,254.554,455.319,3.50,4.04,7.71,12.26,3.275217,U.S.,2702.488
202,2018-11-01,2687.995,726.304,756.296,595.468,609.927,4.32,4.51,7.35,9.43,4.091000,U.S.,2656.502
203,2018-12-01,2958.554,755.975,743.958,762.819,695.802,4.89,5.46,7.77,9.63,4.041667,U.S.,2756.095
204,2019-01-01,3379.295,791.035,834.116,949.438,804.706,4.16,5.04,7.75,9.43,3.123182,U.S.,2750.413
205,2019-02-01,2983.892,710.003,769.182,805.830,698.877,3.79,4.65,7.61,9.47,2.687500,U.S.,2506.257
206,2019-03-01,2882.561,740.796,792.262,685.904,663.599,3.59,4.33,7.47,9.48,2.948571,U.S.,2775.301
207,2019-04-01,2182.901,667.363,724.048,327.124,464.366,2.98,4.02,7.77,10.92,2.647143,U.S.,2707.738